# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DadHive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DadHive
pod 'AWSS3'
pod 'SDWebImage'
pod 'SkyFloatingLabelTextField'
pod 'NextGrowingTextView'
pod 'APESuperHUD', :git => 'https://github.com/apegroup/APESuperHUD.git'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'IQKeyboardManagerSwift'
pod 'Alamofire', '~> 4.7'
pod 'AWSCore'
pod 'ObjectMapper', '~> 3.1'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Firebase', '~> 5.0'
pod 'Firebase/Core', '~> 5.0'
pod 'Firebase/Auth', '~> 5.0'
pod 'Firebase/Database', '~> 5.0'
pod 'Firebase/Storage', '~> 5.0'
pod 'Firebase/Firestore', '~> 5.0'
pod 'Firebase/Messaging', '~> 5.0'
pod 'Firebase/AdMob', '~> 5.0'
pod 'Firebase/Invites', '~> 5.0'
pod 'Firebase/RemoteConfig', '~> 5.0'
pod 'Firebase/Performance', '~> 5.0'
pod 'FirebaseUI', '~> 5.0'
pod 'Cachable'
pod 'CVCalendar'
pod 'SVProgressHUD'
pod 'FontAwesome.swift'
pod 'Fuse'
pod 'GeoFire', '~> 3.0'
pod 'Geofirestore'
pod 'CountryList'
pod 'JSQMessagesViewController'
pod 'GiphyCoreSDK'
pod 'Kingfisher'
pod 'SwiftGifOrigin', '~> 1.6.1'
pod 'Pulsator'
pod 'ImageSlideshow/SDWebImage'
pod 'Hero'
pod 'ImageSlideshow/Alamofire'
pod 'ImageSlideshow', '~> 1.6'
pod 'Poi'
pod 'Instabug'
pod 'GoogleSignIn'
pod 'DatePicker', '1.0.0'

end
